#!/bin/bash
# =============================================================================
# OpenObserve APM Setup Script
# =============================================================================
# This script helps configure OpenObserve for different VPS sizes

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRESETS_DIR="$SCRIPT_DIR/presets"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║           OpenObserve APM Configuration Setup                 ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_presets() {
    echo -e "${YELLOW}Available VPS Presets:${NC}"
    echo ""
    echo "  1) 4GB  - Development/Testing (<5,000 events/min)"
    echo "  2) 8GB  - Light Production, 1-10 apps (<20,000 events/min)"
    echo "  3) 12GB - Medium Production, 10-30 apps (<100,000 events/min)"
    echo "  4) 24GB - Heavy Production, 30-100 apps (<500,000 events/min)"
    echo ""
}

select_preset() {
    local choice=$1
    local preset_file=""
    
    case $choice in
        1|4gb|4GB)
            preset_file="4gb.env"
            ;;
        2|8gb|8GB)
            preset_file="8gb.env"
            ;;
        3|12gb|12GB)
            preset_file="12gb.env"
            ;;
        4|24gb|24GB)
            preset_file="24gb.env"
            ;;
        *)
            echo -e "${RED}Invalid selection: $choice${NC}"
            return 1
            ;;
    esac
    
    echo "$preset_file"
}

merge_env_files() {
    local preset_file=$1
    local target_file="$SCRIPT_DIR/.env"
    local example_file="$SCRIPT_DIR/.env.example"
    
    # Verify preset file exists and is readable
    local preset_path="$PRESETS_DIR/$preset_file"
    if [[ ! -r "$preset_path" ]]; then
        echo -e "${RED}Error:${NC} Preset file '$preset_path' does not exist or is not readable." >&2
        exit 1
    fi
    
    # Start with .env.example as base
    if [[ -f "$target_file" ]]; then
        echo -e "${YELLOW}Existing .env found. Backing up to .env.backup${NC}"
        cp "$target_file" "$target_file.backup"
    fi
    
    if [[ -f "$example_file" ]]; then
        cp "$example_file" "$target_file"
    else
        echo -e "${RED}Missing required .env.example file in ${SCRIPT_DIR}.${NC}"
        echo -e "${RED}.env.example must define mandatory settings such as OPENOBSERVE_DOMAIN, LETSENCRYPT_EMAIL, etc.${NC}"
        echo -e "${RED}Please restore or create .env.example before running this script again.${NC}"
        exit 1
    fi
    
    # Check if default password is being used
    if grep -q "ZO_ROOT_USER_PASSWORD=ChangeMe_StrongPassword123!" "$example_file"; then
        echo ""
        echo -e "${YELLOW}⚠️  WARNING:${NC} .env.example contains the default OpenObserve password"
        echo -e "${YELLOW}   Please change ZO_ROOT_USER_PASSWORD in .env before deploying to production!${NC}"
        echo ""
    fi
    
    # Append preset variables
    echo "" >> "$target_file"
    echo "# ==============================================================================" >> "$target_file"
    echo "# VPS RESOURCE PRESET (auto-generated by setup.sh)" >> "$target_file"
    echo "# ==============================================================================" >> "$target_file"
    cat "$preset_path" >> "$target_file"
    
    echo -e "${GREEN}✓ Configuration written to .env${NC}"
}

interactive_setup() {
    print_header
    print_presets
    
    read -p "Select your VPS size (1-4 or 4gb/8gb/12gb/24gb): " choice
    
    preset_file=$(select_preset "$choice")
    if [[ $? -ne 0 ]]; then
        exit 1
    fi
    
    echo ""
    echo -e "${GREEN}Selected preset: $preset_file${NC}"
    echo ""
    
    merge_env_files "$preset_file"
    
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Edit .env to configure your domains, email, and OpenObserve credentials"
    echo "  2. Run: ./start.sh"
    echo ""
    echo -e "${GREEN}Setup complete!${NC}"
}

# CLI mode: ./setup.sh 8gb
cli_setup() {
    local preset=$1
    
    preset_file=$(select_preset "$preset")
    if [[ $? -ne 0 ]]; then
        echo "Usage: $0 [4gb|8gb|12gb|24gb]"
        exit 1
    fi
    
    merge_env_files "$preset_file"
    
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Edit .env to configure your domains, email, and OpenObserve credentials"
    echo "  2. Run: ./start.sh"
    echo ""
    echo -e "${GREEN}Setup complete!${NC}"
}

# Main
if [[ $# -eq 0 ]]; then
    interactive_setup
else
    cli_setup "$1"
fi
